on:
  push:
    branches:
      - 'master'
  workflow_dispatch: 

name: publish

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: Install mdbook and addons
        run: cargo install mdbook mdbook-admonish

      - name: Build book
        run: |
          # This assumes your book is in the root of your repository.
          # Just add a `cd` here if you need to change to another directory.
          mdbook build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.WIKI_CF_PAGES_TOKEN }}
          accountId: ${{ secrets.WIKI_CF_ACCOUNT_ID }}
          command: pages deploy book --project-name=${{ vars.WIKI_CF_PROJECT_NAME }}
