on:
  push:
    branches:
      - 'master'
  workflow_dispatch: 

name: publish

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Build
        run: mkdocs build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.WIKI_CF_PAGES_TOKEN }}
          accountId: ${{ secrets.WIKI_CF_ACCOUNT_ID }}
          command: pages deploy site --project-name=${{ vars.WIKI_CF_PROJECT_NAME }}
